{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "grafana.fullname" . }}-openbao-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.targetSecret }}
  data:
    {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .path }}
        property: {{ .property }}
    {{- end }}
{{- end }}